variable "name" {}
variable "region" {}
variable "site_key_name" {}
variable "site_public_key" {}
variable "vpc_cidr" {}
variable "legacy_azs" {}
variable "azs" {}
variable "public_subnets" {}
variable "private_subnets" {}
